In [1]:
import pandas as pd
import numpy as np

In [2]:
import random

In [3]:
from datetime import datetime, timedelta

In [4]:
# =========================================
# 2. CONFIGURACIÓN
# =========================================

random.seed(42)
np.random.seed(42)

n_publicaciones = 1000000

In [5]:
# 3. DATOS BASE
influencers = [
    "ana_viaja",
    "cancun_life",
    "playas_mex",
    "travel_girl",
    "sunset_lover",
    "turismo_cancun",
    "beach_vibes",
    "luxury_trip"
]

tipos_post = [
    "foto",
    "reel",
    "historia",
    "video"
]

In [6]:
# 4. GENERAR EL DATASET
dataset = pd.DataFrame({
    
    "influencer": [
        random.choice(influencers)
        for _ in range(n_publicaciones)
    ],
    
    "likes": [
        random.randint(100, 50000)
        for _ in range(n_publicaciones)
    ],
    
    "comentarios": [
        random.randint(0, 5000)
        for _ in range(n_publicaciones)
    ],
    
    "fecha": [
        datetime(2025,1,1) + timedelta(days=random.randint(0,365))
        for _ in range(n_publicaciones)
    ],
    
    "tipo_post": [
        random.choice(tipos_post)
        for _ in range(n_publicaciones)
    ]
})

In [7]:
# 5. VER EL DATASET
dataset.head()

     influencer  likes  comentarios      fecha tipo_post
0   cancun_life  36506         4212 2025-09-08     video
1     ana_viaja   1293         2614 2025-12-27     video
2  sunset_lover  20478         4785 2025-02-05      reel
3   travel_girl  34225          525 2025-07-04      foto
4   travel_girl  24897         3838 2025-04-28      reel

In [8]:
# 6. TAMAÑO DEL DATASET
dataset.shape

(1000000, 5)

In [9]:
# 7. INFORMACIÓN GENERAL
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   influencer   1000000 non-null  str
 1   likes        1000000 non-null  int64
 2   comentarios  1000000 non-null  int64
 3   fecha        1000000 non-null  datetime64[us]
 4   tipo_post    1000000 non-null  str
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 38.1 MB

In [10]:
# 8. ESTADÍSTICAS
dataset.describe()

                likes     comentarios                       fecha
count  1000000.000000  1000000.000000                     1000000
mean     25042.815864     2498.366509  2025-07-02 10:11:27.081599
min        100.000000        0.000000         2025-01-01 00:00:00
25%      12591.000000     1247.000000         2025-04-02 00:00:00
50%      25030.000000     2497.500000         2025-07-02 00:00:00
75%      37524.000000     3751.000000         2025-10-02 00:00:00
max      50000.000000     5000.000000         2026-01-01 00:00:00
std      14400.763826     1444.887981                         NaN

In [11]:
# 9. PROMEDIO DE LIKES
dataset["likes"].mean()

np.float64(25042.815864)

In [12]:
# 10. PROMEDIO DE COMENTARIOS
dataset["comentarios"].mean()

np.float64(2498.366509)

In [13]:
# 11. TIPO DE POST MÁS USADO
dataset["tipo_post"].value_counts()

tipo_post
foto        250482
reel        250246
historia    250017
video       249255
Name: count, dtype: int64

In [14]:
# 12. INFLUENCER CON MÁS POSTS
dataset["influencer"].value_counts()

influencer
sunset_lover      125521
cancun_life       125404
turismo_cancun    125362
ana_viaja         125233
luxury_trip       124846
playas_mex        124714
beach_vibes       124692
travel_girl       124228
Name: count, dtype: int64

In [15]:
# 13. TOP 10 POSTS CON MÁS LIKES
dataset.sort_values(by="likes", ascending=False).head(10)

          influencer  likes  comentarios      fecha tipo_post
809724  sunset_lover  50000         2339 2025-08-03     video
803618  sunset_lover  50000           96 2025-12-07      reel
656400  sunset_lover  50000          171 2025-01-18  historia
875097     ana_viaja  50000         2614 2025-08-04      reel
623135     ana_viaja  50000         3202 2025-10-24      foto
40403     playas_mex  50000         1765 2025-05-03  historia
490178   beach_vibes  50000          399 2025-08-01     video
422107   travel_girl  50000         2461 2025-10-08      foto
245887    playas_mex  50000         1020 2025-12-20      reel
147053    playas_mex  50000          300 2025-02-22      foto

In [16]:
# 14. EXPORTAR A CSV
dataset.to_csv("instagram_dataset.csv", index=False)